name: Create Release Mediatek Filogic
on:
  push:
    tags:
      - "v*.*.*"
    branches:
      - main

jobs:
  build:
    name: "v${{ matrix.tag }} - ${{ matrix.pkgarch }} :: ${{ matrix.target }}/${{ matrix.subtarget }} build"
    runs-on: Linux
    strategy:
      matrix:
        tag: ['23.05.4']
        pkgarch: ['aarch64_cortex-a53']
        target: ['mediatek']
        subtarget: ['filogic']
    steps:
      - uses: actions/checkout@v4
        with:
          repository: openwrt/openwrt
          ref: v${{ matrix.tag }}
          fetch-depth: 0

      - name: Check Environment
        run: |
          echo "Current working directory: $(pwd)"
          echo "Available disk space:"
          df -h
          echo "List of files:"
          ls -la

      - name: Update and install feeds
        run: |
          pkgarch=${{ matrix.pkgarch }}
          target=${{ matrix.target }}
          subtarget=${{ matrix.subtarget }}
          echo "pkgarch: ${pkgarch}, target: ${target}, subtarget: ${subtarget}"

          # Clean previous builds
          rm -rf bin/packages/${pkgarch}/awgopenwrt/ || true
          rm -rf bin/targets/${target}/${subtarget}/packages/ || true

          # Fetch feeds
          wget https://downloads.openwrt.org/releases/${{ matrix.tag }}/targets/${target}/${subtarget}/feeds.buildinfo -O feeds.conf || { echo "Failed to fetch feeds.buildinfo"; exit 1; }
          echo "src-git awgopenwrt https://github.com/lolo6oT/awg-openwrt.git" >> ./feeds.conf
          ./scripts/feeds update -a || { echo "Failed to update feeds"; exit 1; }
          ./scripts/feeds install -a || { echo "Failed to install feeds"; exit 1; }

          # Fetch config
          wget https://downloads.openwrt.org/releases/${{ matrix.tag }}/targets/${target}/${subtarget}/config.buildinfo -O .config || { echo "Failed to fetch config.buildinfo"; exit 1; }
          make defconfig || { echo "make defconfig failed"; exit 1; }

      - name: Trigger Compilation
        run: |
          echo "Starting compilation..."
          export FORCE_UNSAFE_CONFIGURE=1
          echo "CONFIG_PACKAGE_kmod-amneziawg=m" >> .config
          echo "CONFIG_PACKAGE_amneziawg-tools=y" >> .config
          echo "CONFIG_PACKAGE_luci-proto-amneziawg=y" >> .config
          echo "CONFIG_PACKAGE_amneziawg-go=y" >> .config
          if [[ $(uname -m) == "aarch64" ]]; then
            echo 'CONFIG_GOLANG_EXTERNAL_BOOTSTRAP_ROOT="/usr/local/go/bin/go"' >> .config
            echo 'CONFIG_GOLANG_BUILD_CACHE_DIR=""' >> .config
          fi
          make defconfig || { echo "Second make defconfig failed"; exit 1; }

          echo "Downloading packages and building..."
          make -j $(nproc) V=sc download world || { echo "Download and build failed"; exit 1; }

      - name: Make IPK packages
        run: |
          echo "Building IPK packages..."
          make -j $(nproc) package/amneziawg-tools/{clean,download,prepare,compile} || { echo "Building amneziawg-tools failed"; exit 1; }
          make -j $(nproc) package/amneziawg-go/{clean,download,prepare,compile} || { echo "Building amneziawg-go failed"; exit 1; }
          make -j $(nproc) package/kmod-amneziawg/{clean,download,prepare,compile} || { echo "Building kmod-amneziawg failed"; exit 1; }
          make -j $(nproc) package/luci-proto-amneziawg/{clean,download,prepare,compile} || { echo "Building luci-proto-amneziawg failed"; exit 1; }

      - name: Prepare artifacts
        run: |
          tag_name=${{ github.ref_name }}
          mkdir -p awgrelease
          postfix="${tag_name}_v${{ matrix.tag }}_${{ matrix.pkgarch }}_${{ matrix.target }}_${{ matrix.subtarget }}"
          cp bin/packages/${{ matrix.pkgarch }}/awgopenwrt/amneziawg-tools_*.ipk awgrelease/amneziawg-tools_${postfix}.ipk || { echo "Failed to copy amneziawg-tools"; exit 1; }
          cp bin/packages/${{ matrix.pkgarch }}/awgopenwrt/amneziawg-go_*.ipk awgrelease/amneziawg-go_${postfix}.ipk || { echo "Failed to copy amneziawg-go"; exit 1; }
          cp bin/packages/${{ matrix.pkgarch }}/awgopenwrt/luci-proto-amneziawg_*.ipk awgrelease/luci-proto-amneziawg_${postfix}.ipk || { echo "Failed to copy luci-proto-amneziawg"; exit 1; }
          cp bin/targets/${{ matrix.target }}/${{ matrix.subtarget }}/packages/kmod-amneziawg_*.ipk awgrelease/kmod-amneziawg_${postfix}.ipk || { echo "Failed to copy kmod-amneziawg"; exit 1; }

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: awgrelease/*.ipk

      - name: Cleanup
        run: |
          rm feeds.conf || true
          rm -rf awgrelease || true
